services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fastgrab-dev
    container_name: fastgrab-dev
    hostname: fastgrab-dev
    init: true
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    environment:
      DISPLAY: ":99"
      SCREEN_GEOMETRY: "1920x1080x24"
      VNC_PORT: "5900"
    ports:
      - "5901:5900"
    command: ["start-desktop"]

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fastgrab-dev
    init: true
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    command: ["xvfb-run", "-a", "-s", "-screen 0 1280x1024x24", "pytest", "-v", "tests"]

  benchmark:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fastgrab-dev
    init: true
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    environment:
      DISPLAY: ":99"
      SCREEN_GEOMETRY: "3840x2160x24"
    command: ["start-desktop", "python", "examples/benchmark.py"]

volumes:
  pip-cache:
